package services

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"

	"sunipip-router-agent/internal/api"

	"gopkg.in/yaml.v3"
)

const clashConfigPath = "/etc/clash/config.yaml"

// ClashService manages Clash proxy configuration.
type ClashService struct {
	logger *slog.Logger
}

// NewClashService creates a new Clash service manager.
func NewClashService(logger *slog.Logger) *ClashService {
	return &ClashService{logger: logger}
}

// clashConfigYAML is the top-level Clash config structure.
type clashConfigYAML struct {
	Port               int                   `yaml:"port"`
	TProxyPort         int                   `yaml:"tproxy-port"`
	AllowLAN           bool                  `yaml:"allow-lan"`
	Mode               string                `yaml:"mode"`
	LogLevel           string                `yaml:"log-level"`
	ExternalController string                `yaml:"external-controller,omitempty"`
	DNS                clashDNS              `yaml:"dns"`
	Proxies            []clashProxyYAML      `yaml:"proxies"`
	ProxyGroups        []clashProxyGroupYAML `yaml:"proxy-groups,omitempty"`
	Rules              []string              `yaml:"rules"`
}

type clashProxyGroupYAML struct {
	Name     string   `yaml:"name"`
	Type     string   `yaml:"type"`
	Proxies  []string `yaml:"proxies"`
	URL      string   `yaml:"url,omitempty"`
	Interval int      `yaml:"interval,omitempty"`
}

type clashDNS struct {
	Enable       bool     `yaml:"enable"`
	Listen       string   `yaml:"listen"`
	EnhancedMode string   `yaml:"enhanced-mode"`
	FakeIPRange  string   `yaml:"fake-ip-range"`
	Nameserver   []string `yaml:"nameserver"`
}

type clashProxyYAML struct {
	Name     string `yaml:"name"`
	Type     string `yaml:"type"`
	Server   string `yaml:"server"`
	Port     int    `yaml:"port"`
	Username string `yaml:"username,omitempty"`
	Password string `yaml:"password,omitempty"`
}

// Apply writes the Clash config and reloads the service only if config changed.
func (s *ClashService) Apply(ctx context.Context, cfg api.ClashConfig, configVersion int) error {
	s.logger.Info("Applying Clash configuration", "proxies", len(cfg.Proxies), "rules", len(cfg.Rules))

	changed, err := s.writeConfigIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write clash config: %w", err)
	}

	if !s.unitExists(ctx) {
		s.logger.Warn("clash.service unit not found, skipping reload")
		return nil
	}

	if changed {
		s.logger.Info("Clash config changed, restarting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("reload clash: %w", err)
		}
	} else if !s.IsRunning(ctx) {
		s.logger.Warn("Clash not running, starting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("start clash: %w", err)
		}
	} else {
		s.logger.Debug("Clash config unchanged, skipping restart")
	}

	s.logger.Info("Clash configuration applied successfully")
	return nil
}

// writeConfigIfChanged generates the Clash YAML config and writes it only if
// different from the existing file. Returns true if the file was written.
func (s *ClashService) writeConfigIfChanged(cfg api.ClashConfig) (bool, error) {
	clashCfg := clashConfigYAML{
		Port:               7890,
		TProxyPort:         7893,
		AllowLAN:           true,
		Mode:               "rule",
		LogLevel:           "info",
		ExternalController: "127.0.0.1:9090",
		DNS: clashDNS{
			Enable:       true,
			Listen:       "0.0.0.0:1053",
			EnhancedMode: "fake-ip",
			FakeIPRange:  "198.18.0.1/16",
			Nameserver:   []string{"1.1.1.1", "1.0.0.1"},
		},
	}

	for _, p := range cfg.Proxies {
		proxy := clashProxyYAML{
			Name:   p.Name,
			Type:   p.Type,
			Server: p.Server,
			Port:   p.Port,
		}
		if p.Username != "" {
			proxy.Username = p.Username
		}
		if p.Password != "" {
			proxy.Password = p.Password
		}
		clashCfg.Proxies = append(clashCfg.Proxies, proxy)
	}

	for _, g := range cfg.ProxyGroups {
		clashCfg.ProxyGroups = append(clashCfg.ProxyGroups, clashProxyGroupYAML{
			Name:    g.Name,
			Type:    g.Type,
			Proxies: g.Proxies,
		})
	}

	for _, r := range cfg.Rules {
		var rule string
		if r.Value != "" {
			rule = fmt.Sprintf("%s,%s,%s", r.Type, r.Value, r.Proxy)
		} else {
			rule = fmt.Sprintf("%s,%s", r.Type, r.Proxy)
		}
		clashCfg.Rules = append(clashCfg.Rules, rule)
	}

	data, err := yaml.Marshal(clashCfg)
	if err != nil {
		return false, fmt.Errorf("marshal clash config: %w", err)
	}

	header := "# Generated by SuniPIP Router Agent\n# DO NOT EDIT - This file is managed automatically\n"
	newContent := append([]byte(header), data...)

	existing, _ := os.ReadFile(clashConfigPath)
	if string(existing) == string(newContent) {
		return false, nil
	}

	if err := os.MkdirAll("/etc/clash", 0755); err != nil {
		return false, fmt.Errorf("create clash config dir: %w", err)
	}

	if err := writeFileAtomic(clashConfigPath, newContent, 0644); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote Clash config", "path", clashConfigPath)
	return true, nil
}

// reload restarts the Clash service.
func (s *ClashService) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "clash")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart clash: %w (output: %s)", err, string(output))
	}
	return nil
}

// unitExists checks whether the clash.service systemd unit is known.
func (s *ClashService) unitExists(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "cat", "clash")
	return cmd.Run() == nil
}

// IsInstalled reports whether the clash systemd unit exists.
func (s *ClashService) IsInstalled(ctx context.Context) bool {
	return s.unitExists(ctx)
}

// IsRunning checks if Clash is currently running.
func (s *ClashService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "clash")
	return cmd.Run() == nil
}

// GetCurrentConfig reads the current Clash config for drift detection.
func (s *ClashService) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(clashConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
