package services

import (
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"sunipip-router-agent/internal/api"
)

const dnsmasqConfigDir = "/etc/dnsmasq.d"

// DHCPService manages dnsmasq per-VLAN DHCP configuration.
type DHCPService struct {
	logger *slog.Logger
}

// NewDHCPService creates a new DHCP service manager.
func NewDHCPService(logger *slog.Logger) *DHCPService {
	return &DHCPService{logger: logger}
}

// Apply writes dnsmasq config files for all VLANs and reloads the service.
func (s *DHCPService) Apply(ctx context.Context, cfg api.NetworkConfig, configVersion int) error {
	s.logger.Info("Applying dnsmasq configuration", "vlans", len(cfg.VLANs))

	if err := os.MkdirAll(dnsmasqConfigDir, 0755); err != nil {
		return fmt.Errorf("create dnsmasq config dir: %w", err)
	}
	os.MkdirAll("/etc/sunipip/dhcp-hosts.d", 0755)

	// Remove existing agent-managed configs
	if err := s.cleanManagedConfigs(); err != nil {
		s.logger.Warn("Failed to clean old dnsmasq configs", "error", err)
	}

	// Write global upstream DNS config: all queries go to 1.1.1.1
	if err := s.writeGlobalDNSConfig(); err != nil {
		return fmt.Errorf("write global DNS config: %w", err)
	}

	// Pin /etc/resolv.conf so the router itself also uses 1.1.1.1
	s.pinResolvConf()

	// Write management DHCP config
	if cfg.Management.DHCP.RangeStart != "" {
		if err := s.writeInterfaceConfig("management", cfg.Management.Interface, cfg.Management.DHCP, cfg.Management.IP); err != nil {
			return fmt.Errorf("write management DHCP config: %w", err)
		}
	}

	// Write trunk (AP) DHCP config, with optional WiFi subnet
	if cfg.Trunk.DHCP.RangeStart != "" {
		if err := s.writeTrunkConfig(cfg.Trunk); err != nil {
			return fmt.Errorf("write trunk DHCP config: %w", err)
		}
	}

	// Write wired DHCP config
	if cfg.Wired.DHCP.RangeStart != "" {
		if err := s.writeInterfaceConfig("wired", cfg.Wired.Interface, cfg.Wired.DHCP, cfg.Wired.IP); err != nil {
			return fmt.Errorf("write wired DHCP config: %w", err)
		}
	}

	// Write per-VLAN configs
	for _, vlan := range cfg.VLANs {
		if err := s.writeVLANConfig(vlan); err != nil {
			return fmt.Errorf("write DHCP config for VLAN %d: %w", vlan.VLANID, err)
		}
	}

	// Reload dnsmasq (skip if not installed)
	if !s.unitExists(ctx) {
		s.logger.Warn("dnsmasq.service unit not found, skipping reload")
	} else if err := s.reload(ctx); err != nil {
		return fmt.Errorf("reload dnsmasq: %w", err)
	}

	s.logger.Info("dnsmasq configuration applied successfully")
	return nil
}

// writeVLANConfig writes a per-VLAN dnsmasq config file.
// For the v2 IP-pool scheme (single VLAN with /16), uses static-only DHCP
// so that only RADIUS-authenticated MACs with dhcp-host entries get IPs.
func (s *DHCPService) writeVLANConfig(vlan api.VLANConfig) error {
	gateway := vlan.DHCP.Gateway
	dns := vlan.DHCP.DNS

	if gateway == "" {
		gateway = ipFromCIDR(vlan.IP)
	}
	if dns == "" {
		dns = ipFromCIDR(vlan.IP)
	}

	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString(fmt.Sprintf("# VLAN %d\n", vlan.VLANID))
	b.WriteString(fmt.Sprintf("interface=%s\n", vlan.Bridge))

	_, ipNet, _ := net.ParseCIDR(vlan.IP)
	prefixLen, _ := ipNet.Mask.Size()

	if prefixLen <= 16 {
		// v2: large subnet, static-only DHCP (IPs assigned by RADIUS post-auth hook)
		netmask := cidrToNetmask(vlan.IP)
		b.WriteString(fmt.Sprintf("dhcp-range=%s,static,%s,%s\n",
			gateway, netmask, vlan.DHCP.Lease))
	} else {
		// v1 compat: small subnet, normal range
		netmask := cidrToNetmask(vlan.IP)
		b.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n",
			vlan.DHCP.RangeStart, vlan.DHCP.RangeEnd, netmask, vlan.DHCP.Lease))
	}

	b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,3,%s\n", vlan.Bridge, gateway))
	b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,6,%s\n", vlan.Bridge, dns))
	b.WriteString("dhcp-hostsdir=/etc/sunipip/dhcp-hosts.d/\n")

	path := filepath.Join(dnsmasqConfigDir, fmt.Sprintf("sunipip-vlan-%d.conf", vlan.VLANID))
	if err := writeFileAtomic(path, []byte(b.String()), 0644); err != nil {
		return err
	}

	s.logger.Debug("Wrote dnsmasq VLAN config", "vlan_id", vlan.VLANID, "path", path)
	return nil
}

// writeTrunkConfig writes dnsmasq config for the trunk interface.
// In v2 flat mode, this includes both AP management DHCP and WiFi static DHCP.
func (s *DHCPService) writeTrunkConfig(trunk api.TrunkConfig) error {
	netmask := cidrToNetmask(trunk.IP)
	gateway := trunk.DHCP.Gateway
	dns := trunk.DHCP.DNS
	if gateway == "" {
		gateway = ipFromCIDR(trunk.IP)
	}
	if dns == "" {
		dns = ipFromCIDR(trunk.IP)
	}

	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# trunk interface (AP management + WiFi clients)\n")
	b.WriteString(fmt.Sprintf("interface=%s\n", trunk.Interface))

	// Management DHCP range — only enabled for v1 (no wifi_subnet).
	// v2 devices: AP uses static IP, no dynamic range needed.
	// Keeping mgmt range open on v2 causes WiFi clients to grab 10.20.0.x IPs.
	if trunk.WifiSubnet == nil || trunk.WifiSubnet.IP == "" {
		b.WriteString(fmt.Sprintf("dhcp-range=set:mgmt,%s,%s,%s,%s\n",
			trunk.DHCP.RangeStart, trunk.DHCP.RangeEnd, netmask, trunk.DHCP.Lease))
		b.WriteString(fmt.Sprintf("dhcp-option=tag:mgmt,3,%s\n", gateway))
		b.WriteString(fmt.Sprintf("dhcp-option=tag:mgmt,6,%s\n", dns))
	}

	// v2: WiFi client subnet — static-only DHCP (MACs assigned by RADIUS post-auth hook)
	if trunk.WifiSubnet != nil && trunk.WifiSubnet.IP != "" {
		wifiGateway := trunk.WifiSubnet.DHCP.Gateway
		if wifiGateway == "" {
			wifiGateway = ipFromCIDR(trunk.WifiSubnet.IP)
		}
		wifiDNS := trunk.WifiSubnet.DHCP.DNS
		if wifiDNS == "" {
			wifiDNS = ipFromCIDR(trunk.WifiSubnet.IP)
		}
		wifiNetmask := cidrToNetmask(trunk.WifiSubnet.IP)
		wifiLease := trunk.WifiSubnet.DHCP.Lease
		if wifiLease == "" {
			wifiLease = "1h"
		}

		b.WriteString(fmt.Sprintf("\n# WiFi client subnet (static-only, IPs assigned by RADIUS hook)\n"))
		b.WriteString(fmt.Sprintf("dhcp-range=set:wifi,%s,static,%s,%s\n",
			wifiGateway, wifiNetmask, wifiLease))
		b.WriteString(fmt.Sprintf("dhcp-option=tag:wifi,3,%s\n", wifiGateway))
		b.WriteString(fmt.Sprintf("dhcp-option=tag:wifi,6,%s\n", wifiDNS))
		b.WriteString("dhcp-hostsdir=/etc/sunipip/dhcp-hosts.d/\n")
	}

	path := filepath.Join(dnsmasqConfigDir, "sunipip-trunk.conf")
	if err := writeFileAtomic(path, []byte(b.String()), 0644); err != nil {
		return err
	}
	s.logger.Debug("Wrote dnsmasq trunk config", "path", path, "has_wifi", trunk.WifiSubnet != nil)
	return nil
}

// writeInterfaceConfig writes a dnsmasq config for a named interface (management, wired).
func (s *DHCPService) writeInterfaceConfig(name, iface string, dhcp api.DHCPConfig, ifaceIP string) error {
	netmask := cidrToNetmask(ifaceIP)
	gateway := dhcp.Gateway
	dns := dhcp.DNS

	if gateway == "" {
		gateway = ipFromCIDR(ifaceIP)
	}
	if dns == "" {
		dns = ipFromCIDR(ifaceIP)
	}

	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString(fmt.Sprintf("# %s interface\n", name))
	b.WriteString(fmt.Sprintf("interface=%s\n", iface))
	b.WriteString(fmt.Sprintf("dhcp-range=%s,%s,%s,%s\n",
		dhcp.RangeStart, dhcp.RangeEnd, netmask, dhcp.Lease))
	b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,3,%s\n", iface, gateway))
	b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,6,%s\n", iface, dns))

	path := filepath.Join(dnsmasqConfigDir, fmt.Sprintf("sunipip-%s.conf", name))
	if err := writeFileAtomic(path, []byte(b.String()), 0644); err != nil {
		return err
	}

	s.logger.Debug("Wrote dnsmasq interface config", "name", name, "path", path)
	return nil
}

// writeGlobalDNSConfig writes a dnsmasq drop-in that forces upstream DNS to 1.1.1.1.
func (s *DHCPService) writeGlobalDNSConfig() error {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# Global upstream DNS\n")
	b.WriteString("no-resolv\n")
	b.WriteString("server=1.1.1.1\n")
	b.WriteString("server=1.0.0.1\n")
	b.WriteString("# DHCP event logging (DISCOVER/OFFER/REQUEST/ACK/NAK)\n")
	b.WriteString("log-dhcp\n")

	path := filepath.Join(dnsmasqConfigDir, "sunipip-global-dns.conf")
	if err := writeFileAtomic(path, []byte(b.String()), 0644); err != nil {
		return err
	}
	s.logger.Debug("Wrote global DNS config", "path", path)
	return nil
}

// pinResolvConf writes /etc/resolv.conf so the router itself uses 1.1.1.1.
func (s *DHCPService) pinResolvConf() {
	content := "# Managed by SuniPIP Router Agent\nnameserver 1.1.1.1\nnameserver 1.0.0.1\n"
	if err := os.WriteFile("/etc/resolv.conf", []byte(content), 0644); err != nil {
		s.logger.Warn("Failed to write /etc/resolv.conf", "error", err)
	}
}

// cleanManagedConfigs removes all sunipip-managed dnsmasq config files.
func (s *DHCPService) cleanManagedConfigs() error {
	entries, err := os.ReadDir(dnsmasqConfigDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), "sunipip-") && strings.HasSuffix(entry.Name(), ".conf") {
			path := filepath.Join(dnsmasqConfigDir, entry.Name())
			if err := os.Remove(path); err != nil {
				s.logger.Warn("Failed to remove old config", "path", path, "error", err)
			}
		}
	}
	return nil
}

// reload restarts the dnsmasq service.
func (s *DHCPService) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "dnsmasq")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart dnsmasq: %w (output: %s)", err, string(output))
	}
	return nil
}

// Restart restarts the dnsmasq service (for scheduled maintenance).
func (s *DHCPService) Restart(ctx context.Context) error {
	if !s.unitExists(ctx) {
		return nil
	}
	s.logger.Info("Restarting dnsmasq (scheduled maintenance)")
	return s.reload(ctx)
}

// unitExists checks whether the dnsmasq.service systemd unit is known.
func (s *DHCPService) unitExists(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "cat", "dnsmasq")
	return cmd.Run() == nil
}

// IsInstalled reports whether the dnsmasq systemd unit exists.
func (s *DHCPService) IsInstalled(ctx context.Context) bool {
	return s.unitExists(ctx)
}

// IsRunning checks if dnsmasq is currently running.
func (s *DHCPService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "dnsmasq")
	return cmd.Run() == nil
}

// cidrToNetmask converts a CIDR prefix to a dotted-decimal netmask.
func cidrToNetmask(cidr string) string {
	_, ipNet, err := net.ParseCIDR(cidr)
	if err != nil {
		return "255.255.255.0" // fallback
	}
	mask := ipNet.Mask
	return fmt.Sprintf("%d.%d.%d.%d", mask[0], mask[1], mask[2], mask[3])
}

// ipFromCIDR extracts the IP address from a CIDR notation string.
func ipFromCIDR(cidr string) string {
	ip, _, err := net.ParseCIDR(cidr)
	if err != nil {
		parts := strings.SplitN(cidr, "/", 2)
		return parts[0]
	}
	return ip.String()
}
