package services

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"

	"sunipip-router-agent/internal/api"
)

const nftablesConfigPath = "/etc/nftables.conf"

// FirewallService manages nftables rules.
type FirewallService struct {
	logger *slog.Logger
}

// NewFirewallService creates a new firewall service manager.
func NewFirewallService(logger *slog.Logger) *FirewallService {
	return &FirewallService{logger: logger}
}

// Apply writes the nftables config and reloads the ruleset.
func (s *FirewallService) Apply(ctx context.Context, cfg api.NetworkConfig, configVersion int) error {
	s.logger.Info("Applying nftables configuration")

	content := s.generateConfig(cfg)

	if err := writeFileAtomic(nftablesConfigPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write nftables config: %w", err)
	}

	// Check if nft binary exists
	if _, err := exec.LookPath("nft"); err != nil {
		s.logger.Warn("nft binary not found, skipping firewall apply")
		return nil
	}

	// Apply the ruleset
	cmd := exec.CommandContext(ctx, "nft", "-f", nftablesConfigPath)
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("apply nftables: %w (output: %s)", err, string(output))
	}

	s.logger.Info("nftables configuration applied successfully")
	return nil
}

// generateConfig builds the nftables ruleset.
func (s *FirewallService) generateConfig(cfg api.NetworkConfig) string {
	var b strings.Builder

	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")
	b.WriteString("flush ruleset\n\n")

	// Filter table — accept all, no restrictive rules
	b.WriteString("table inet filter {\n")
	b.WriteString("    chain input {\n")
	b.WriteString("        type filter hook input priority 0; policy accept;\n")
	b.WriteString("    }\n\n")
	b.WriteString("    chain forward {\n")
	b.WriteString("        type filter hook forward priority 0; policy accept;\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// NAT table
	b.WriteString("table inet nat {\n")
	b.WriteString("    chain postrouting {\n")
	b.WriteString("        type nat hook postrouting priority 100;\n")
	b.WriteString(fmt.Sprintf("        oifname \"%s\" masquerade\n", cfg.WAN.Interface))
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// TProxy mangle table — redirect VLAN traffic through Clash
	b.WriteString("table ip mangle {\n")
	b.WriteString("    chain clash-tproxy {\n")
	b.WriteString("        type filter hook prerouting priority mangle; policy accept;\n\n")

	b.WriteString(fmt.Sprintf("        iifname \"%s\" return\n", cfg.Management.Interface))
	b.WriteString(fmt.Sprintf("        iifname \"%s\" return\n", cfg.Wired.Interface))
	b.WriteString(fmt.Sprintf("        iifname \"%s\" return\n", cfg.WAN.Interface))
	b.WriteString(fmt.Sprintf("        iifname \"%s\" return\n", cfg.Trunk.Interface))
	b.WriteString("        iif \"lo\" return\n")
	b.WriteString("        iifname \"wg*\" return\n\n")

	b.WriteString("        meta mark 0x539 return\n\n")

	b.WriteString("        ip daddr 127.0.0.0/8 return\n")
	b.WriteString("        ip daddr 10.10.0.0/16 return\n")
	b.WriteString("        ip daddr 10.20.0.0/24 return\n")
	b.WriteString("        ip daddr 172.10.0.0/24 return\n")
	b.WriteString("        ip daddr 100.64.1.0/24 return\n")
	b.WriteString("        ip daddr 255.255.255.255 return\n")
	b.WriteString("        udp dport { 67, 68 } return\n\n")

	b.WriteString("        iifname \"br-vlan*\" meta l4proto tcp tproxy to 127.0.0.1:7893 meta mark set 0x1 accept\n")
	b.WriteString("        iifname \"br-vlan*\" meta l4proto udp tproxy to 127.0.0.1:7893 meta mark set 0x1 accept\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// DNS redirect — VLAN clients use Clash fake-ip DNS
	b.WriteString("table ip nat {\n")
	b.WriteString("    chain clash-dns {\n")
	b.WriteString("        type nat hook prerouting priority dstnat; policy accept;\n\n")
	b.WriteString("        iifname \"br-vlan*\" udp dport 53 redirect to :1053\n")
	b.WriteString("        iifname \"br-vlan*\" tcp dport 53 redirect to :1053\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")

	return b.String()
}

// IsRunning checks if nftables service is active.
func (s *FirewallService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "nftables")
	return cmd.Run() == nil
}

// GetCurrentConfig reads the current nftables config for drift detection.
func (s *FirewallService) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(nftablesConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
