package services

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"os/user"
	"strconv"
	"strings"

	"sunipip-router-agent/internal/api"
)

const (
	freeRadiusAuthorizePath = "/etc/freeradius/3.0/mods-config/files/authorize"
	freeRadiusClientsPath   = "/etc/freeradius/3.0/clients.conf"
)

// FreeRadiusService manages FreeRadius configuration.
type FreeRadiusService struct {
	logger *slog.Logger
}

// NewFreeRadiusService creates a new FreeRadius service manager.
func NewFreeRadiusService(logger *slog.Logger) *FreeRadiusService {
	return &FreeRadiusService{logger: logger}
}

// Apply writes the FreeRadius authorize file and clients config, then reloads
// the service only if the config actually changed. Unnecessary restarts cause
// all WiFi clients to re-authenticate.
func (s *FreeRadiusService) Apply(ctx context.Context, cfg api.FreeRadiusConfig, configVersion int) error {
	s.logger.Info("Applying FreeRadius configuration", "users", len(cfg.Users), "clients", len(cfg.Clients))

	authChanged, err := s.writeAuthorizeIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write authorize: %w", err)
	}

	clientsChanged, err := s.writeClientsIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write clients: %w", err)
	}

	s.chownFiles("freerad", freeRadiusAuthorizePath, freeRadiusClientsPath)

	if !s.unitExists(ctx) {
		s.logger.Warn("freeradius.service unit not found, skipping reload")
	} else if authChanged || clientsChanged {
		s.logger.Info("FreeRadius config changed, restarting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("reload freeradius: %w", err)
		}
	} else if !s.IsRunning(ctx) {
		s.logger.Warn("FreeRadius not running, starting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("start freeradius: %w", err)
		}
	} else {
		s.logger.Debug("FreeRadius config unchanged, skipping restart")
	}

	s.logger.Info("FreeRadius configuration applied successfully")
	return nil
}

// writeAuthorizeIfChanged generates the authorize file and writes it only if
// the content differs from what is already on disk. Returns true if the file
// was actually written (i.e., content changed or file was missing).
func (s *FreeRadiusService) writeAuthorizeIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for i, user := range cfg.Users {
		if i > 0 {
			b.WriteString("\n")
		}
		if user.Label != "" {
			safeLabel := strings.ReplaceAll(strings.ReplaceAll(user.Label, "\n", " "), "\r", "")
			b.WriteString(fmt.Sprintf("# %s\n", safeLabel))
		}
		escapedPassword := strings.ReplaceAll(strings.ReplaceAll(user.Password, `\`, `\\`), `"`, `\"`)
		if user.MaxDevices > 0 {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\", Simultaneous-Use := %d\n", user.Username, escapedPassword, user.MaxDevices))
		} else {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\"\n", user.Username, escapedPassword))
		}
		b.WriteString("    Tunnel-Type = VLAN,\n")
		b.WriteString("    Tunnel-Medium-Type = IEEE-802,\n")
		b.WriteString(fmt.Sprintf("    Tunnel-Private-Group-ID = %d\n", user.VLANID))
	}

	b.WriteString("\nDEFAULT Auth-Type := Reject\n")
	b.WriteString("    Reply-Message = \"Access Denied\"\n")

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusAuthorizePath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusAuthorizePath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius authorize file", "path", freeRadiusAuthorizePath, "users", len(cfg.Users))
	return true, nil
}

// writeClientsIfChanged generates clients.conf and writes only if changed.
func (s *FreeRadiusService) writeClientsIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for _, client := range cfg.Clients {
		safeName := strings.ReplaceAll(strings.ReplaceAll(client.Name, "\n", ""), " ", "_")
		b.WriteString(fmt.Sprintf("client %s {\n", safeName))
		b.WriteString(fmt.Sprintf("    ipaddr = %s\n", client.IP))
		b.WriteString(fmt.Sprintf("    secret = %s\n", client.Secret))
		b.WriteString("}\n\n")
	}

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusClientsPath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusClientsPath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius clients config", "path", freeRadiusClientsPath, "clients", len(cfg.Clients))
	return true, nil
}

// reload restarts the FreeRadius service.
func (s *FreeRadiusService) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "freeradius")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart freeradius: %w (output: %s)", err, string(output))
	}
	return nil
}

// Restart restarts the FreeRadius service (for scheduled maintenance).
func (s *FreeRadiusService) Restart(ctx context.Context) error {
	if !s.unitExists(ctx) {
		return nil
	}
	s.logger.Info("Restarting FreeRadius (scheduled maintenance)")
	return s.reload(ctx)
}

// EnableAuthLog ensures auth logging and bad-password logging are enabled in radiusd.conf.
func (s *FreeRadiusService) EnableAuthLog(ctx context.Context) {
	const radiusdConf = "/etc/freeradius/3.0/radiusd.conf"
	data, err := os.ReadFile(radiusdConf)
	if err != nil {
		return
	}
	content := string(data)
	changed := false

	if strings.Contains(content, "auth = no") {
		content = strings.Replace(content, "auth = no", "auth = yes", 1)
		changed = true
	}
	if strings.Contains(content, "auth_badpass = no") {
		content = strings.Replace(content, "auth_badpass = no", "auth_badpass = yes", 1)
		changed = true
	}

	if !changed {
		return
	}
	if err := os.WriteFile(radiusdConf, []byte(content), 0640); err != nil {
		s.logger.Warn("Failed to enable auth logging", "error", err)
		return
	}
	s.chownFiles("freerad", radiusdConf)
	s.logger.Info("Enabled FreeRadius auth + badpass logging")
	s.reload(ctx)
}

// unitExists checks whether the freeradius.service systemd unit is known.
func (s *FreeRadiusService) unitExists(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "cat", "freeradius")
	return cmd.Run() == nil
}

// IsInstalled reports whether the freeradius systemd unit exists.
func (s *FreeRadiusService) IsInstalled(ctx context.Context) bool {
	return s.unitExists(ctx)
}

// IsRunning checks if FreeRadius is currently running.
func (s *FreeRadiusService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "freeradius")
	return cmd.Run() == nil
}

func (s *FreeRadiusService) chownFiles(username string, paths ...string) {
	u, err := user.Lookup(username)
	if err != nil {
		s.logger.Warn("Cannot look up user for chown, skipping", "user", username, "error", err)
		return
	}
	uid, _ := strconv.Atoi(u.Uid)
	gid, _ := strconv.Atoi(u.Gid)
	for _, p := range paths {
		if err := os.Chown(p, uid, gid); err != nil {
			s.logger.Warn("Failed to chown file", "path", p, "user", username, "error", err)
		}
	}
}

// GetCurrentConfig reads the current authorize file for drift detection.
func (s *FreeRadiusService) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(freeRadiusAuthorizePath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
