package services

import (
	"bufio"
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"os/user"
	"strconv"
	"strings"
	"syscall"
	"time"

	"sunipip-router-agent/internal/api"
)

const (
	freeRadiusAuthorizePath = "/etc/freeradius/3.0/mods-config/files/authorize"
	freeRadiusClientsPath   = "/etc/freeradius/3.0/clients.conf"
	dhcpHookModulePath      = "/etc/freeradius/3.0/mods-enabled/dhcp_hook"
	dhcpHookScriptPath      = "/etc/sunipip/radius-dhcp-hook.sh"
	userIpPoolPath          = "/etc/sunipip/user-ip-pool.conf"
	dhcpHostsDirPath        = "/etc/sunipip/dhcp-hosts.d"
	dhcpHostsFilePath       = "/etc/sunipip/dhcp-hosts.d/hosts"
	dhcpHostsOldFilePath    = "/etc/sunipip/dhcp-hosts.conf"
)

// FreeRadiusService manages FreeRadius configuration.
type FreeRadiusService struct {
	logger *slog.Logger
}

// NewFreeRadiusService creates a new FreeRadius service manager.
func NewFreeRadiusService(logger *slog.Logger) *FreeRadiusService {
	return &FreeRadiusService{logger: logger}
}

// Apply writes the FreeRadius authorize file, clients config, DHCP hook module
// and IP pool config, then reloads the service only if config actually changed.
func (s *FreeRadiusService) Apply(ctx context.Context, cfg api.FreeRadiusConfig, configVersion int) error {
	s.logger.Info("Applying FreeRadius configuration", "users", len(cfg.Users), "clients", len(cfg.Clients))

	authChanged, err := s.writeAuthorizeIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write authorize: %w", err)
	}

	clientsChanged, err := s.writeClientsIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write clients: %w", err)
	}

	os.MkdirAll(dhcpHostsDirPath, 0755)
	s.migrateDHCPHostsDir()

	hookChanged, err := s.writeDHCPHook(cfg)
	if err != nil {
		return fmt.Errorf("write dhcp hook: %w", err)
	}

	s.writeDnsmasqReloadUnits(ctx)

	s.chownFiles("freerad", freeRadiusAuthorizePath, freeRadiusClientsPath, dhcpHookModulePath,
		dhcpHostsFilePath, dhcpHookScriptPath, "/etc/sunipip/user-ip-pool.conf", dhcpHostsDirPath, "/etc/sunipip")
	os.MkdirAll("/var/log/sunipip", 0755)
	s.chownFiles("freerad", "/var/log/sunipip")
	logFile := "/var/log/sunipip/radius-dhcp-hook.log"
	if _, err := os.Stat(logFile); err == nil {
		s.chownFiles("freerad", logFile)
	} else {
		os.WriteFile(logFile, nil, 0644)
		s.chownFiles("freerad", logFile)
	}

	if !s.unitExists(ctx) {
		s.logger.Warn("freeradius.service unit not found, skipping reload")
	} else if authChanged || clientsChanged || hookChanged {
		s.logger.Info("FreeRadius config changed, restarting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("reload freeradius: %w", err)
		}
	} else if s.needsRestart(ctx) {
		s.logger.Info("FreeRadius needs restart (config out of sync)")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("restart freeradius: %w", err)
		}
	} else if !s.IsRunning(ctx) {
		s.logger.Warn("FreeRadius not running, starting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("start freeradius: %w", err)
		}
	} else {
		s.logger.Debug("FreeRadius config unchanged, skipping restart")
	}

	s.logger.Info("FreeRadius configuration applied successfully")
	return nil
}

// needsRestart checks if FreeRadius config files are newer than the running process.
func (s *FreeRadiusService) needsRestart(ctx context.Context) bool {
	if !s.IsRunning(ctx) {
		return false
	}
	// Check if dhcp_hook module exists but FreeRadius started before the sites-enabled/default was modified
	sitesInfo, err := os.Stat("/etc/freeradius/3.0/sites-enabled/default")
	if err != nil {
		return false
	}
	if _, err := os.Stat(dhcpHookModulePath); err != nil {
		return false
	}
	out, err := exec.CommandContext(ctx, "systemctl", "show", "freeradius", "--property=ActiveEnterTimestamp").Output()
	if err != nil {
		return false
	}
	ts := strings.TrimPrefix(strings.TrimSpace(string(out)), "ActiveEnterTimestamp=")
	startTime, err := time.Parse("Mon 2006-01-02 15:04:05 MST", ts)
	if err != nil {
		return false
	}
	return sitesInfo.ModTime().After(startTime)
}

// writeAuthorizeIfChanged generates the authorize file and writes it only if
// the content differs from what is already on disk. Returns true if the file
// was actually written (i.e., content changed or file was missing).
func (s *FreeRadiusService) writeAuthorizeIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for i, user := range cfg.Users {
		if i > 0 {
			b.WriteString("\n")
		}
		if user.Label != "" {
			safeLabel := strings.ReplaceAll(strings.ReplaceAll(user.Label, "\n", " "), "\r", "")
			b.WriteString(fmt.Sprintf("# %s\n", safeLabel))
		}
		escapedPassword := strings.ReplaceAll(strings.ReplaceAll(user.Password, `\`, `\\`), `"`, `\"`)
		if user.MaxDevices > 0 {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\", Simultaneous-Use := %d\n", user.Username, escapedPassword, user.MaxDevices))
		} else {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\"\n", user.Username, escapedPassword))
		}
		if user.VLANID > 0 {
			// v1 compat: assign VLAN when dynamic_vlan is enabled on AP
			b.WriteString("    Tunnel-Type = VLAN,\n")
			b.WriteString("    Tunnel-Medium-Type = IEEE-802,\n")
			b.WriteString(fmt.Sprintf("    Tunnel-Private-Group-ID = %d\n", user.VLANID))
		}
	}

	b.WriteString("\nDEFAULT Auth-Type := Reject\n")
	b.WriteString("    Reply-Message = \"Access Denied\"\n")

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusAuthorizePath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusAuthorizePath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius authorize file", "path", freeRadiusAuthorizePath, "users", len(cfg.Users))
	return true, nil
}

// writeClientsIfChanged generates clients.conf and writes only if changed.
func (s *FreeRadiusService) writeClientsIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for _, client := range cfg.Clients {
		safeName := strings.ReplaceAll(strings.ReplaceAll(client.Name, "\n", ""), " ", "_")
		b.WriteString(fmt.Sprintf("client %s {\n", safeName))
		b.WriteString(fmt.Sprintf("    ipaddr = %s\n", client.IP))
		b.WriteString(fmt.Sprintf("    secret = %s\n", client.Secret))
		b.WriteString("}\n\n")
	}

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusClientsPath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusClientsPath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius clients config", "path", freeRadiusClientsPath, "clients", len(cfg.Clients))
	return true, nil
}

// reload restarts the FreeRadius service.
func (s *FreeRadiusService) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "freeradius")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart freeradius: %w (output: %s)", err, string(output))
	}
	return nil
}

// Restart restarts the FreeRadius service (for scheduled maintenance).
func (s *FreeRadiusService) Restart(ctx context.Context) error {
	if !s.unitExists(ctx) {
		return nil
	}
	s.logger.Info("Restarting FreeRadius (scheduled maintenance)")
	return s.reload(ctx)
}

// EnableAuthLog ensures auth logging and bad-password logging are enabled in radiusd.conf.
func (s *FreeRadiusService) EnableAuthLog(ctx context.Context) {
	const radiusdConf = "/etc/freeradius/3.0/radiusd.conf"
	data, err := os.ReadFile(radiusdConf)
	if err != nil {
		return
	}
	content := string(data)
	changed := false

	if strings.Contains(content, "auth = no") {
		content = strings.Replace(content, "auth = no", "auth = yes", 1)
		changed = true
	}
	if strings.Contains(content, "auth_badpass = no") {
		content = strings.Replace(content, "auth_badpass = no", "auth_badpass = yes", 1)
		changed = true
	}

	if !changed {
		return
	}
	if err := os.WriteFile(radiusdConf, []byte(content), 0640); err != nil {
		s.logger.Warn("Failed to enable auth logging", "error", err)
		return
	}
	s.chownFiles("freerad", radiusdConf)
	s.logger.Info("Enabled FreeRadius auth + badpass logging")
	s.reload(ctx)
}

// unitExists checks whether the freeradius.service systemd unit is known.
func (s *FreeRadiusService) unitExists(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "cat", "freeradius")
	return cmd.Run() == nil
}

// IsInstalled reports whether the freeradius systemd unit exists.
func (s *FreeRadiusService) IsInstalled(ctx context.Context) bool {
	return s.unitExists(ctx)
}

// IsRunning checks if FreeRadius is currently running.
func (s *FreeRadiusService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "freeradius")
	return cmd.Run() == nil
}

func (s *FreeRadiusService) chownFiles(username string, paths ...string) {
	u, err := user.Lookup(username)
	if err != nil {
		s.logger.Warn("Cannot look up user for chown, skipping", "user", username, "error", err)
		return
	}
	uid, _ := strconv.Atoi(u.Uid)
	gid, _ := strconv.Atoi(u.Gid)
	for _, p := range paths {
		if err := os.Chown(p, uid, gid); err != nil {
			s.logger.Warn("Failed to chown file", "path", p, "user", username, "error", err)
		}
	}
}

// writeDHCPHook writes the FreeRadius exec module, post-auth script, and
// user-IP pool config. Returns true if any file changed.
func (s *FreeRadiusService) writeDHCPHook(cfg api.FreeRadiusConfig) (bool, error) {
	hasAllocatedIPs := false
	for _, u := range cfg.Users {
		if len(u.AllocatedIPs) > 0 {
			hasAllocatedIPs = true
			break
		}
	}
	if !hasAllocatedIPs {
		return false, nil
	}

	os.MkdirAll("/etc/sunipip", 0755)

	changed := false

	// 1. Write FreeRadius exec module for DHCP hook
	moduleContent := `exec dhcp_hook {
    wait = yes
    program = "` + dhcpHookScriptPath + `"
    input_pairs = request
    shell_escape = yes
    timeout = 5
}
`
	existing, _ := os.ReadFile(dhcpHookModulePath)
	if string(existing) != moduleContent {
		if err := writeFileAtomic(dhcpHookModulePath, []byte(moduleContent), 0640); err != nil {
			return false, fmt.Errorf("write dhcp_hook module: %w", err)
		}
		changed = true
	}

	// 2. Ensure dhcp_hook is in post-auth section
	if s.ensurePostAuthHook() {
		changed = true
	}

	// 3. Write user-IP pool config
	var poolBuf strings.Builder
	poolBuf.WriteString("# Generated by SuniPIP Router Agent\n")
	for _, u := range cfg.Users {
		if len(u.AllocatedIPs) == 0 {
			continue
		}
		poolBuf.WriteString(fmt.Sprintf("%s %s\n", u.Username, strings.Join(u.AllocatedIPs, ",")))
	}
	poolContent := poolBuf.String()

	existingPool, _ := os.ReadFile(userIpPoolPath)
	if string(existingPool) != poolContent {
		if err := writeFileAtomic(userIpPoolPath, []byte(poolContent), 0644); err != nil {
			return false, fmt.Errorf("write user IP pool: %w", err)
		}
		changed = true
	}

	// 4. Write the post-auth hook script
	scriptChanged, err := s.writeHookScript()
	if err != nil {
		return false, err
	}
	if scriptChanged {
		changed = true
	}

	// 5. Ensure shared files are writable by freerad (hook runs as freerad user)
	for _, f := range []string{"/tmp/sunipip-dhcp-hook.lock", "/tmp/sunipip-grace-macs"} {
		fh, err := os.OpenFile(f, os.O_CREATE|os.O_WRONLY, 0666)
		if err == nil {
			fh.Close()
		}
		os.Chmod(f, 0666)
	}
	os.Chmod(dhcpHostsFilePath, 0777)

	// 6. Clean dhcp-hosts.conf: remove entries whose IPs are not in any user's pool
	allValidIPs := make(map[string]bool)
	for _, u := range cfg.Users {
		for _, ip := range u.AllocatedIPs {
			allValidIPs[ip] = true
		}
	}
	if err := s.cleanDHCPHosts(allValidIPs); err != nil {
		s.logger.Warn("Failed to clean dhcp-hosts", "error", err)
	}

	return changed, nil
}

// cleanDHCPHosts removes dhcp-host entries whose IPs are no longer in any user's pool.
// This handles account deletion: old MAC→IP entries for deleted accounts get purged.
func (s *FreeRadiusService) cleanDHCPHosts(validIPs map[string]bool) error {
	data, err := os.ReadFile(dhcpHostsFilePath)
	if err != nil {
		if os.IsNotExist(err) {
			writeFileAtomic(dhcpHostsFilePath, []byte("# Managed by RADIUS post-auth hook\n"), 0777)
			return nil
		}
		return err
	}

	var kept []string
	removed := 0
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			kept = append(kept, line)
			continue
		}
		// Format: MAC,IP,LEASE (migrate from old dhcp-host=MAC,IP,LEASE)
		cleaned := strings.TrimPrefix(trimmed, "dhcp-host=")
		parts := strings.Split(cleaned, ",")
		if len(parts) >= 2 {
			ip := parts[1]
			if !validIPs[ip] {
				removed++
				s.logger.Info("Removing stale dhcp-host entry", "line", trimmed)
				continue
			}
		}
		if cleaned != trimmed {
			removed++ // count as change to trigger rewrite
		}
		kept = append(kept, cleaned)
	}

	if removed > 0 {
		newContent := strings.Join(kept, "\n")
		if !strings.HasSuffix(newContent, "\n") {
			newContent += "\n"
		}
		if err := writeFileAtomic(dhcpHostsFilePath, []byte(newContent), 0777); err != nil {
			return err
		}
		s.logger.Info("Cleaned dhcp-hosts.conf", "removed", removed)
	}

	return nil
}

// ensurePostAuthHook ensures dhcp_hook is in the post-auth section (not authenticate).
// Returns true if the file was modified.
func (s *FreeRadiusService) ensurePostAuthHook() bool {
	const sitesDefault = "/etc/freeradius/3.0/sites-enabled/default"
	data, err := os.ReadFile(sitesDefault)
	if err != nil {
		return false
	}
	content := string(data)

	// Find where post-auth section starts
	postAuthIdx := strings.Index(content, "\npost-auth {")
	if postAuthIdx < 0 {
		postAuthIdx = strings.Index(content, "\npost-auth{")
	}
	if postAuthIdx < 0 {
		s.logger.Warn("Cannot inject dhcp_hook: post-auth section not found")
		return false
	}

	// Check if dhcp_hook is already in the post-auth section (correct position)
	postAuthContent := content[postAuthIdx:]
	if strings.Contains(postAuthContent, "dhcp_hook") {
		return false
	}

	// Remove dhcp_hook from wrong position (e.g. authenticate section)
	if strings.Contains(content, "\tdhcp_hook\n") {
		content = strings.ReplaceAll(content, "\tdhcp_hook\n", "")
		s.logger.Info("Removed dhcp_hook from wrong section")
		// Recalculate post-auth position after removal
		postAuthIdx = strings.Index(content, "\npost-auth {")
		if postAuthIdx < 0 {
			postAuthIdx = strings.Index(content, "\npost-auth{")
		}
		if postAuthIdx < 0 {
			return false
		}
	}

	// Find exec in post-auth section and insert after it
	postAuthContent = content[postAuthIdx:]
	execIdx := strings.Index(postAuthContent, "\n\texec\n")
	if execIdx < 0 {
		s.logger.Warn("Cannot inject dhcp_hook: exec not found in post-auth section")
		return false
	}
	insertPos := postAuthIdx + execIdx + len("\n\texec\n")
	content = content[:insertPos] + "\tdhcp_hook\n" + content[insertPos:]
	os.WriteFile(sitesDefault, []byte(content), 0640)
	s.chownFiles("freerad", sitesDefault)
	s.logger.Info("Added dhcp_hook to FreeRadius post-auth section")
	return true
}

// writeHookScript writes the post-auth DHCP hook shell script.
// systemd path unit watches the hosts file and sends SIGHUP to dnsmasq.
func (s *FreeRadiusService) writeHookScript() (bool, error) {
	script := `#!/bin/bash
# SuniPIP RADIUS Post-Auth DHCP Hook
# Writes MAC→IP to hosts file; systemd path unit sends SIGHUP to dnsmasq.

LOGFILE="/var/log/sunipip/radius-dhcp-hook.log"
DHCP_HOSTS="/etc/sunipip/dhcp-hosts.d/hosts"
POOL="/etc/sunipip/user-ip-pool.conf"
LEASES="/var/lib/misc/dnsmasq.leases"
LOCKFILE="/tmp/sunipip-dhcp-hook.lock"

MAC=$(echo "$CALLING_STATION_ID" | tr -d '"')
USER=$(echo "$USER_NAME" | tr -d '"')

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOGFILE"; }

[ -z "$MAC" ] || [ -z "$USER" ] && exit 0

MAC=$(echo "$MAC" | tr 'A-Z-' 'a-z:' | sed 's/[^a-f0-9:]//g')
[ -z "$MAC" ] && exit 0

# Fast path: if this MAC already has an entry, skip everything
if grep -q "^${MAC}," "$DHCP_HOSTS" 2>/dev/null; then
    exit 0
fi

log "AUTH: user=$USER mac=$MAC (new)"

exec 9>"$LOCKFILE"
flock -w 5 9 || { log "ERROR: lock timeout"; exit 0; }

LINE=$(awk -v u="$USER" '$1 == u {print; exit}' "$POOL" 2>/dev/null)
if [ -z "$LINE" ]; then
    log "ERROR: no pool for user=$USER"
    flock -u 9
    exit 0
fi

IPS=$(echo "$LINE" | cut -d' ' -f2)
IFS=',' read -ra IP_ARRAY <<< "$IPS"

TMP="/tmp/sunipip-dhcp-hosts.tmp.$$"
cp "$DHCP_HOSTS" "$TMP" 2>/dev/null || echo "# Managed by RADIUS post-auth hook" > "$TMP"

# Assign first IP that is free in BOTH hosts file AND lease file
# Note: stale entry cleanup is handled by the agent's CleanStaleHosts (checks ARP + lease + grace)
FOUND=0
for IP in "${IP_ARRAY[@]}"; do
    # Skip if IP is in hosts file (assigned to another MAC)
    grep -q ",${IP}," "$TMP" 2>/dev/null && continue
    # Skip if IP is leased to a different MAC (avoid lease conflict)
    LEASE_MAC=$(awk -v ip="$IP" '$3 == ip {print $2}' "$LEASES" 2>/dev/null)
    if [ -n "$LEASE_MAC" ] && [ "$LEASE_MAC" != "$MAC" ]; then
        log "SKIP: ip=$IP leased to $LEASE_MAC, trying next"
        continue
    fi
    echo "${MAC},${IP},30m" >> "$TMP"
    cat "$TMP" > "$DHCP_HOSTS"
    rm -f "$TMP"
    IFACE=$(ip -o addr show to "${IP%.*}.0/24" 2>/dev/null | awk '{print $2}' | head -1)
    [ -z "$IFACE" ] && IFACE=$(ip -o addr show to "10.10.0.0/16" 2>/dev/null | awk '{print $2}' | head -1)
    [ -n "$IFACE" ] && ip neigh replace "$IP" lladdr "$MAC" dev "$IFACE" nud reachable 2>/dev/null
    # Protect this MAC from cleanup for 120s (device needs time to complete DHCP)
    echo "${MAC} $(date +%s)" >> /tmp/sunipip-grace-macs
    log "ASSIGNED: user=$USER mac=$MAC ip=$IP"
    FOUND=1
    break
done

if [ "$FOUND" = "0" ]; then
    # All IPs blocked by leases from dead MACs — request restart to clear
    touch /tmp/sunipip-dnsmasq-restart-needed
    # Assign the first hosts-free IP anyway; restart will clear the conflicting lease
    for IP in "${IP_ARRAY[@]}"; do
        if ! grep -q ",${IP}," "$TMP" 2>/dev/null; then
            echo "${MAC},${IP},30m" >> "$TMP"
            cat "$TMP" > "$DHCP_HOSTS"
            rm -f "$TMP"
            echo "${MAC} $(date +%s)" >> /tmp/sunipip-grace-macs
            log "ASSIGNED (restart pending): user=$USER mac=$MAC ip=$IP"
            FOUND=1
            break
        fi
    done
    [ "$FOUND" = "0" ] && rm -f "$TMP" && log "ERROR: all IPs occupied for user=$USER"
fi

flock -u 9
exit 0
`
	existing, _ := os.ReadFile(dhcpHookScriptPath)
	if string(existing) == script {
		return false, nil
	}

	if err := writeFileAtomic(dhcpHookScriptPath, []byte(script), 0755); err != nil {
		return false, fmt.Errorf("write hook script: %w", err)
	}
	s.logger.Info("Wrote RADIUS DHCP hook script")
	return true, nil
}

// migrateDHCPHostsDir moves dhcp-hosts.conf from the old flat file into dhcp-hosts.d/.
func (s *FreeRadiusService) migrateDHCPHostsDir() {
	if _, err := os.Stat(dhcpHostsOldFilePath); err != nil {
		return
	}
	if _, err := os.Stat(dhcpHostsFilePath); err == nil {
		os.Remove(dhcpHostsOldFilePath)
		return
	}
	data, err := os.ReadFile(dhcpHostsOldFilePath)
	if err != nil {
		return
	}
	if err := writeFileAtomic(dhcpHostsFilePath, data, 0777); err != nil {
		s.logger.Warn("Failed to migrate dhcp-hosts to dir", "error", err)
		return
	}
	os.Remove(dhcpHostsOldFilePath)
	s.logger.Info("Migrated dhcp-hosts.conf to dhcp-hosts.d/hosts")
}

// writeDnsmasqReloadUnits creates a systemd path unit that watches the DHCP
// hosts file and a oneshot service that sends SIGHUP to dnsmasq on change.
// This runs as root (systemd), so no sudo needed from the freerad hook.
func (s *FreeRadiusService) writeDnsmasqReloadUnits(ctx context.Context) {
	pathUnit := `[Unit]
Description=Watch SuniPIP DHCP hosts file for changes

[Path]
PathChanged=/etc/sunipip/dhcp-hosts.d/hosts

[Install]
WantedBy=multi-user.target
`
	serviceUnit := `[Unit]
Description=Reload dnsmasq after DHCP hosts change

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'kill -HUP $(cat /run/dnsmasq/dnsmasq.pid 2>/dev/null || cat /var/run/dnsmasq/dnsmasq.pid 2>/dev/null) 2>/dev/null; true'
`
	pathPath := "/etc/systemd/system/sunipip-dnsmasq-reload.path"
	svcPath := "/etc/systemd/system/sunipip-dnsmasq-reload.service"

	oldPath, _ := os.ReadFile(pathPath)
	oldSvc, _ := os.ReadFile(svcPath)

	if string(oldPath) == pathUnit && string(oldSvc) == serviceUnit {
		return
	}

	os.WriteFile(pathPath, []byte(pathUnit), 0644)
	os.WriteFile(svcPath, []byte(serviceUnit), 0644)

	exec.CommandContext(ctx, "systemctl", "daemon-reload").Run()
	exec.CommandContext(ctx, "systemctl", "enable", "--now", "sunipip-dnsmasq-reload.path").Run()
	s.logger.Info("Installed systemd dnsmasq reload path unit")
}

// CleanStaleHosts removes hosts entries for MACs no longer present in the ARP table.
// Respects a grace period: MACs recently assigned by the hook are protected for 120s,
// giving devices time to complete DHCP and appear in ARP.
func (s *FreeRadiusService) CleanStaleHosts(ctx context.Context) {
	data, err := os.ReadFile(dhcpHostsFilePath)
	if err != nil {
		return
	}

	arpMACs := s.getAliveMACs()
	if arpMACs == nil {
		return
	}

	// Read grace-protected MACs (written by hook, protected for 120s)
	graceMACs := s.loadGraceMACs()

	// Read active leases: MAC → expiry timestamp
	activeLeases := s.loadActiveLeases()

	var kept []string
	var cleaned []string
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			kept = append(kept, line)
			continue
		}
		mac := strings.SplitN(line, ",", 2)[0]
		if _, alive := arpMACs[mac]; alive {
			kept = append(kept, line)
		} else if _, grace := graceMACs[mac]; grace {
			kept = append(kept, line)
		} else if _, leased := activeLeases[mac]; leased {
			// Not in ARP but lease still active → idle device, keep it
			kept = append(kept, line)
		} else {
			cleaned = append(cleaned, mac)
		}
	}

	// Also check for restart flag from hook (all IPs exhausted by lease conflicts)
	restartFlag := "/tmp/sunipip-dnsmasq-restart-needed"
	hasRestartFlag := false
	if _, err := os.Stat(restartFlag); err == nil {
		hasRestartFlag = true
		os.Remove(restartFlag)
	}

	if len(cleaned) == 0 && !hasRestartFlag {
		return
	}

	if len(cleaned) > 0 {
		for _, mac := range cleaned {
			s.logger.Info("Stale host cleaned", "mac", mac)
		}
		content := strings.Join(kept, "\n") + "\n"
		// Use flock to prevent race with the hook script
		lockFile, err := os.OpenFile("/tmp/sunipip-dhcp-hook.lock", os.O_CREATE|os.O_WRONLY, 0666)
		if err == nil {
			os.Chmod("/tmp/sunipip-dhcp-hook.lock", 0666)
			syscall.Flock(int(lockFile.Fd()), syscall.LOCK_EX)
			writeFileAtomic(dhcpHostsFilePath, []byte(content), 0777)
			syscall.Flock(int(lockFile.Fd()), syscall.LOCK_UN)
			lockFile.Close()
		}
		s.logger.Info("Cleaned stale hosts", "removed", len(cleaned), "remaining", len(kept)-1)
	}

	// Only restart dnsmasq if the hook flagged "all IPs exhausted by leases"
	// Otherwise the file write above triggers systemd path unit → SIGHUP (hot reload)
	if hasRestartFlag {
		// Protect all MACs currently in hosts: after lease truncation they lose lease protection,
		// but they might be valid idle devices. Grace gives them 120s to renew after restart.
		s.graceProtectCurrentHosts()
		for _, lf := range []string{"/var/lib/misc/dnsmasq.leases", "/var/lib/dnsmasq/dnsmasq.leases"} {
			os.Truncate(lf, 0)
		}
		exec.CommandContext(ctx, "systemctl", "restart", "dnsmasq").Run()
		s.logger.Info("Restarted dnsmasq (all IPs were lease-blocked)")
	}
}

// graceProtectCurrentHosts writes all MACs currently in the hosts file to the grace file.
// Called before lease truncation + dnsmasq restart to prevent cleanup from removing
// valid idle devices that temporarily lose both ARP and lease protection.
func (s *FreeRadiusService) graceProtectCurrentHosts() {
	const gracePath = "/tmp/sunipip-grace-macs"
	data, err := os.ReadFile(dhcpHostsFilePath)
	if err != nil {
		return
	}
	now := fmt.Sprintf("%d", time.Now().Unix())
	var lines []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		mac := strings.SplitN(line, ",", 2)[0]
		lines = append(lines, mac+" "+now)
	}
	if len(lines) > 0 {
		existing, _ := os.ReadFile(gracePath)
		content := string(existing) + strings.Join(lines, "\n") + "\n"
		os.WriteFile(gracePath, []byte(content), 0666)
		os.Chmod(gracePath, 0666)
	}
}

// loadGraceMACs reads /tmp/sunipip-grace-macs, returns MACs added within 120s,
// and rewrites the file to remove expired entries.
func (s *FreeRadiusService) loadGraceMACs() map[string]struct{} {
	const gracePath = "/tmp/sunipip-grace-macs"
	const graceDuration = 120
	data, err := os.ReadFile(gracePath)
	if err != nil {
		return nil
	}
	now := time.Now().Unix()
	result := make(map[string]struct{})
	var keptLines []string
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		parts := strings.Fields(line)
		if len(parts) != 2 {
			continue
		}
		ts, err := strconv.ParseInt(parts[1], 10, 64)
		if err != nil {
			continue
		}
		if now-ts < graceDuration {
			result[parts[0]] = struct{}{}
			keptLines = append(keptLines, line)
		}
	}
	// Rewrite to purge expired entries
	if len(keptLines) > 0 {
		os.WriteFile(gracePath, []byte(strings.Join(keptLines, "\n")+"\n"), 0777)
		os.Chmod(gracePath, 0777)
	} else {
		os.Remove(gracePath)
	}
	return result
}

// loadActiveLeases reads dnsmasq lease files and returns MACs with non-expired leases.
// Lease format: expiry_timestamp MAC IP hostname [client_id]
func (s *FreeRadiusService) loadActiveLeases() map[string]struct{} {
	result := make(map[string]struct{})
	now := time.Now().Unix()
	for _, lf := range []string{"/var/lib/misc/dnsmasq.leases", "/var/lib/dnsmasq/dnsmasq.leases"} {
		data, err := os.ReadFile(lf)
		if err != nil {
			continue
		}
		for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
			fields := strings.Fields(line)
			if len(fields) < 3 {
				continue
			}
			expiry, err := strconv.ParseInt(fields[0], 10, 64)
			if err != nil {
				continue
			}
			if expiry > now {
				mac := strings.ToLower(fields[1])
				result[mac] = struct{}{}
			}
		}
	}
	return result
}

func (s *FreeRadiusService) getAliveMACs() map[string]struct{} {
	out, err := exec.Command("ip", "neigh", "show").Output()
	if err != nil {
		return nil
	}
	macs := make(map[string]struct{})
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 5 {
			continue
		}
		state := fields[len(fields)-1]
		if state == "REACHABLE" || state == "STALE" || state == "DELAY" || state == "PROBE" {
			mac := strings.ToLower(fields[4])
			macs[mac] = struct{}{}
		}
	}
	return macs
}

// GetCurrentConfig reads the current authorize file for drift detection.
func (s *FreeRadiusService) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(freeRadiusAuthorizePath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
