package services

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"os/user"
	"strconv"
	"strings"

	"sunipip-router-agent/internal/api"
)

const (
	freeRadiusAuthorizePath = "/etc/freeradius/3.0/mods-config/files/authorize"
	freeRadiusClientsPath   = "/etc/freeradius/3.0/clients.conf"
	dhcpHookModulePath      = "/etc/freeradius/3.0/mods-enabled/dhcp_hook"
	dhcpHookScriptPath      = "/etc/sunipip/radius-dhcp-hook.sh"
	userIpPoolPath          = "/etc/sunipip/user-ip-pool.conf"
	dhcpHostsFilePath       = "/etc/sunipip/dhcp-hosts.conf"
)

// FreeRadiusService manages FreeRadius configuration.
type FreeRadiusService struct {
	logger *slog.Logger
}

// NewFreeRadiusService creates a new FreeRadius service manager.
func NewFreeRadiusService(logger *slog.Logger) *FreeRadiusService {
	return &FreeRadiusService{logger: logger}
}

// Apply writes the FreeRadius authorize file, clients config, DHCP hook module
// and IP pool config, then reloads the service only if config actually changed.
func (s *FreeRadiusService) Apply(ctx context.Context, cfg api.FreeRadiusConfig, configVersion int) error {
	s.logger.Info("Applying FreeRadius configuration", "users", len(cfg.Users), "clients", len(cfg.Clients))

	authChanged, err := s.writeAuthorizeIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write authorize: %w", err)
	}

	clientsChanged, err := s.writeClientsIfChanged(cfg)
	if err != nil {
		return fmt.Errorf("write clients: %w", err)
	}

	hookChanged, err := s.writeDHCPHook(cfg)
	if err != nil {
		return fmt.Errorf("write dhcp hook: %w", err)
	}

	s.chownFiles("freerad", freeRadiusAuthorizePath, freeRadiusClientsPath, dhcpHookModulePath)

	if !s.unitExists(ctx) {
		s.logger.Warn("freeradius.service unit not found, skipping reload")
	} else if authChanged || clientsChanged || hookChanged {
		s.logger.Info("FreeRadius config changed, restarting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("reload freeradius: %w", err)
		}
	} else if !s.IsRunning(ctx) {
		s.logger.Warn("FreeRadius not running, starting")
		if err := s.reload(ctx); err != nil {
			return fmt.Errorf("start freeradius: %w", err)
		}
	} else {
		s.logger.Debug("FreeRadius config unchanged, skipping restart")
	}

	s.logger.Info("FreeRadius configuration applied successfully")
	return nil
}

// writeAuthorizeIfChanged generates the authorize file and writes it only if
// the content differs from what is already on disk. Returns true if the file
// was actually written (i.e., content changed or file was missing).
func (s *FreeRadiusService) writeAuthorizeIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for i, user := range cfg.Users {
		if i > 0 {
			b.WriteString("\n")
		}
		if user.Label != "" {
			safeLabel := strings.ReplaceAll(strings.ReplaceAll(user.Label, "\n", " "), "\r", "")
			b.WriteString(fmt.Sprintf("# %s\n", safeLabel))
		}
		escapedPassword := strings.ReplaceAll(strings.ReplaceAll(user.Password, `\`, `\\`), `"`, `\"`)
		if user.MaxDevices > 0 {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\", Simultaneous-Use := %d\n", user.Username, escapedPassword, user.MaxDevices))
		} else {
			b.WriteString(fmt.Sprintf("%s  Cleartext-Password := \"%s\"\n", user.Username, escapedPassword))
		}
		if user.VLANID > 0 {
			// v1 compat: assign VLAN when dynamic_vlan is enabled on AP
			b.WriteString("    Tunnel-Type = VLAN,\n")
			b.WriteString("    Tunnel-Medium-Type = IEEE-802,\n")
			b.WriteString(fmt.Sprintf("    Tunnel-Private-Group-ID = %d\n", user.VLANID))
		}
	}

	b.WriteString("\nDEFAULT Auth-Type := Reject\n")
	b.WriteString("    Reply-Message = \"Access Denied\"\n")

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusAuthorizePath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusAuthorizePath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius authorize file", "path", freeRadiusAuthorizePath, "users", len(cfg.Users))
	return true, nil
}

// writeClientsIfChanged generates clients.conf and writes only if changed.
func (s *FreeRadiusService) writeClientsIfChanged(cfg api.FreeRadiusConfig) (bool, error) {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	for _, client := range cfg.Clients {
		safeName := strings.ReplaceAll(strings.ReplaceAll(client.Name, "\n", ""), " ", "_")
		b.WriteString(fmt.Sprintf("client %s {\n", safeName))
		b.WriteString(fmt.Sprintf("    ipaddr = %s\n", client.IP))
		b.WriteString(fmt.Sprintf("    secret = %s\n", client.Secret))
		b.WriteString("}\n\n")
	}

	newContent := b.String()

	existing, _ := os.ReadFile(freeRadiusClientsPath)
	if string(existing) == newContent {
		return false, nil
	}

	if err := writeFileAtomic(freeRadiusClientsPath, []byte(newContent), 0640); err != nil {
		return false, err
	}

	s.logger.Debug("Wrote FreeRadius clients config", "path", freeRadiusClientsPath, "clients", len(cfg.Clients))
	return true, nil
}

// reload restarts the FreeRadius service.
func (s *FreeRadiusService) reload(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "freeradius")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("systemctl restart freeradius: %w (output: %s)", err, string(output))
	}
	return nil
}

// Restart restarts the FreeRadius service (for scheduled maintenance).
func (s *FreeRadiusService) Restart(ctx context.Context) error {
	if !s.unitExists(ctx) {
		return nil
	}
	s.logger.Info("Restarting FreeRadius (scheduled maintenance)")
	return s.reload(ctx)
}

// EnableAuthLog ensures auth logging and bad-password logging are enabled in radiusd.conf.
func (s *FreeRadiusService) EnableAuthLog(ctx context.Context) {
	const radiusdConf = "/etc/freeradius/3.0/radiusd.conf"
	data, err := os.ReadFile(radiusdConf)
	if err != nil {
		return
	}
	content := string(data)
	changed := false

	if strings.Contains(content, "auth = no") {
		content = strings.Replace(content, "auth = no", "auth = yes", 1)
		changed = true
	}
	if strings.Contains(content, "auth_badpass = no") {
		content = strings.Replace(content, "auth_badpass = no", "auth_badpass = yes", 1)
		changed = true
	}

	if !changed {
		return
	}
	if err := os.WriteFile(radiusdConf, []byte(content), 0640); err != nil {
		s.logger.Warn("Failed to enable auth logging", "error", err)
		return
	}
	s.chownFiles("freerad", radiusdConf)
	s.logger.Info("Enabled FreeRadius auth + badpass logging")
	s.reload(ctx)
}

// unitExists checks whether the freeradius.service systemd unit is known.
func (s *FreeRadiusService) unitExists(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "cat", "freeradius")
	return cmd.Run() == nil
}

// IsInstalled reports whether the freeradius systemd unit exists.
func (s *FreeRadiusService) IsInstalled(ctx context.Context) bool {
	return s.unitExists(ctx)
}

// IsRunning checks if FreeRadius is currently running.
func (s *FreeRadiusService) IsRunning(ctx context.Context) bool {
	cmd := exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", "freeradius")
	return cmd.Run() == nil
}

func (s *FreeRadiusService) chownFiles(username string, paths ...string) {
	u, err := user.Lookup(username)
	if err != nil {
		s.logger.Warn("Cannot look up user for chown, skipping", "user", username, "error", err)
		return
	}
	uid, _ := strconv.Atoi(u.Uid)
	gid, _ := strconv.Atoi(u.Gid)
	for _, p := range paths {
		if err := os.Chown(p, uid, gid); err != nil {
			s.logger.Warn("Failed to chown file", "path", p, "user", username, "error", err)
		}
	}
}

// writeDHCPHook writes the FreeRadius exec module, post-auth script, and
// user-IP pool config. Returns true if any file changed.
func (s *FreeRadiusService) writeDHCPHook(cfg api.FreeRadiusConfig) (bool, error) {
	hasAllocatedIPs := false
	for _, u := range cfg.Users {
		if len(u.AllocatedIPs) > 0 {
			hasAllocatedIPs = true
			break
		}
	}
	if !hasAllocatedIPs {
		return false, nil
	}

	os.MkdirAll("/etc/sunipip", 0755)

	changed := false

	// 1. Write FreeRadius exec module for DHCP hook
	moduleContent := `exec dhcp_hook {
    wait = yes
    program = "` + dhcpHookScriptPath + `"
    input_pairs = request
    shell_escape = yes
    timeout = 5
}
`
	existing, _ := os.ReadFile(dhcpHookModulePath)
	if string(existing) != moduleContent {
		if err := writeFileAtomic(dhcpHookModulePath, []byte(moduleContent), 0640); err != nil {
			return false, fmt.Errorf("write dhcp_hook module: %w", err)
		}
		changed = true
	}

	// 2. Ensure dhcp_hook is in post-auth section
	s.ensurePostAuthHook()

	// 3. Write user-IP pool config
	var poolBuf strings.Builder
	poolBuf.WriteString("# Generated by SuniPIP Router Agent\n")
	for _, u := range cfg.Users {
		if len(u.AllocatedIPs) == 0 {
			continue
		}
		poolBuf.WriteString(fmt.Sprintf("%s %s\n", u.Username, strings.Join(u.AllocatedIPs, ",")))
	}
	poolContent := poolBuf.String()

	existingPool, _ := os.ReadFile(userIpPoolPath)
	if string(existingPool) != poolContent {
		if err := writeFileAtomic(userIpPoolPath, []byte(poolContent), 0644); err != nil {
			return false, fmt.Errorf("write user IP pool: %w", err)
		}
		changed = true
	}

	// 4. Write the post-auth hook script
	scriptChanged, err := s.writeHookScript()
	if err != nil {
		return false, err
	}
	if scriptChanged {
		changed = true
	}

	// 5. Clean dhcp-hosts.conf: remove entries whose IPs are not in any user's pool
	allValidIPs := make(map[string]bool)
	for _, u := range cfg.Users {
		for _, ip := range u.AllocatedIPs {
			allValidIPs[ip] = true
		}
	}
	if err := s.cleanDHCPHosts(allValidIPs); err != nil {
		s.logger.Warn("Failed to clean dhcp-hosts", "error", err)
	}

	return changed, nil
}

// cleanDHCPHosts removes dhcp-host entries whose IPs are no longer in any user's pool.
// This handles account deletion: old MAC→IP entries for deleted accounts get purged.
func (s *FreeRadiusService) cleanDHCPHosts(validIPs map[string]bool) error {
	data, err := os.ReadFile(dhcpHostsFilePath)
	if err != nil {
		if os.IsNotExist(err) {
			writeFileAtomic(dhcpHostsFilePath, []byte("# Managed by RADIUS post-auth hook\n"), 0644)
			return nil
		}
		return err
	}

	var kept []string
	removed := 0
	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			kept = append(kept, line)
			continue
		}
		// Format: dhcp-host=MAC,IP,LEASE
		parts := strings.Split(trimmed, ",")
		if len(parts) >= 2 {
			ip := parts[1]
			if !validIPs[ip] {
				removed++
				s.logger.Info("Removing stale dhcp-host entry", "line", trimmed)
				continue
			}
		}
		kept = append(kept, line)
	}

	if removed > 0 {
		newContent := strings.Join(kept, "\n")
		if !strings.HasSuffix(newContent, "\n") {
			newContent += "\n"
		}
		if err := writeFileAtomic(dhcpHostsFilePath, []byte(newContent), 0644); err != nil {
			return err
		}
		s.logger.Info("Cleaned dhcp-hosts.conf", "removed", removed)
	}

	return nil
}

// ensurePostAuthHook adds dhcp_hook to the post-auth section if not present.
func (s *FreeRadiusService) ensurePostAuthHook() {
	const sitesDefault = "/etc/freeradius/3.0/sites-enabled/default"
	data, err := os.ReadFile(sitesDefault)
	if err != nil {
		return
	}
	content := string(data)
	if strings.Contains(content, "dhcp_hook") {
		return
	}
	if !strings.Contains(content, "\n\texec\n") {
		s.logger.Warn("Cannot inject dhcp_hook: expected pattern '\\n\\texec\\n' not found in sites-enabled/default")
		return
	}
	content = strings.Replace(content, "\n\texec\n", "\n\texec\n\tdhcp_hook\n", 1)
	os.WriteFile(sitesDefault, []byte(content), 0640)
	s.chownFiles("freerad", sitesDefault)
	s.logger.Info("Added dhcp_hook to FreeRadius post-auth section")
}

// writeHookScript writes the post-auth DHCP hook shell script.
func (s *FreeRadiusService) writeHookScript() (bool, error) {
	script := `#!/bin/bash
# SuniPIP RADIUS Post-Auth DHCP Hook
# Maps authenticated MAC to pre-allocated IP via dnsmasq
# Handles MAC randomization: reclaims IPs from stale MACs (not in ARP table)

LOGFILE="/var/log/sunipip/radius-dhcp-hook.log"
DHCP_HOSTS="/etc/sunipip/dhcp-hosts.conf"
POOL="/etc/sunipip/user-ip-pool.conf"
LOCKFILE="/var/lock/sunipip-dhcp-hook.lock"

mkdir -p /var/log/sunipip

MAC="$CALLING_STATION_ID"
USER="$USER_NAME"

log() { echo "$(date '+%Y-%m-%d %H:%M:%S') $1" >> "$LOGFILE"; }

if [ -z "$MAC" ] || [ -z "$USER" ]; then
    exit 0
fi

MAC=$(echo "$MAC" | tr 'A-Z-' 'a-z:' | sed 's/[^a-f0-9:]//g')

if [ -z "$MAC" ]; then
    log "ERROR: MAC empty after sanitization"
    exit 0
fi

log "AUTH: user=$USER mac=$MAC"

exec 9>"$LOCKFILE"
flock -w 5 9 || { log "ERROR: lock timeout"; exit 0; }

# Check if this MAC already has an entry
if grep -q "^dhcp-host=${MAC}," "$DHCP_HOSTS" 2>/dev/null; then
    log "EXISTING: mac=$MAC"
    flock -u 9
    exit 0
fi

# Get user's allocated IPs from pool file (fixed-string match)
LINE=$(grep -F "${USER} " "$POOL" 2>/dev/null | grep "^${USER} ")
if [ -z "$LINE" ]; then
    log "ERROR: no pool for user=$USER"
    flock -u 9
    exit 0
fi

IPS=$(echo "$LINE" | cut -d' ' -f2)
IFS=',' read -ra IP_ARRAY <<< "$IPS"

# Find first unused IP
FOUND=0
for IP in "${IP_ARRAY[@]}"; do
    if ! grep -q ",${IP}," "$DHCP_HOSTS" 2>/dev/null && ! grep -q ",${IP}$" "$DHCP_HOSTS" 2>/dev/null; then
        echo "dhcp-host=${MAC},${IP},1h" >> "$DHCP_HOSTS"
        kill -HUP $(pidof dnsmasq) 2>/dev/null
        log "ASSIGNED: user=$USER mac=$MAC ip=$IP"
        FOUND=1
        break
    fi
done

if [ "$FOUND" = "0" ]; then
    # All IPs occupied — try to reclaim from stale MACs (not in ARP table)
    # This handles iOS/Android random MAC: old MAC is gone, reclaim its IP
    for IP in "${IP_ARRAY[@]}"; do
        OLD_LINE=$(grep ",${IP}," "$DHCP_HOSTS" 2>/dev/null || grep ",${IP}$" "$DHCP_HOSTS" 2>/dev/null)
        if [ -z "$OLD_LINE" ]; then continue; fi
        OLD_MAC=$(echo "$OLD_LINE" | sed 's/^dhcp-host=//;s/,.*//')
        if [ -z "$OLD_MAC" ]; then continue; fi
        # Check if old MAC is still reachable (in ARP table)
        if ip neigh show 2>/dev/null | grep -qi "$OLD_MAC"; then
            continue
        fi
        # Old MAC is gone — reclaim this IP
        sed -i "/^dhcp-host=${OLD_MAC},/d" "$DHCP_HOSTS"
        echo "dhcp-host=${MAC},${IP},1h" >> "$DHCP_HOSTS"
        kill -HUP $(pidof dnsmasq) 2>/dev/null
        log "RECLAIMED: user=$USER old_mac=$OLD_MAC new_mac=$MAC ip=$IP"
        FOUND=1
        break
    done
fi

if [ "$FOUND" = "0" ]; then
    log "ERROR: all IPs exhausted for user=$USER (all MACs still in ARP)"
fi

flock -u 9
exit 0
`
	existing, _ := os.ReadFile(dhcpHookScriptPath)
	if string(existing) == script {
		return false, nil
	}

	if err := writeFileAtomic(dhcpHookScriptPath, []byte(script), 0755); err != nil {
		return false, fmt.Errorf("write hook script: %w", err)
	}
	s.logger.Info("Wrote RADIUS DHCP hook script")
	return true, nil
}

// GetCurrentConfig reads the current authorize file for drift detection.
func (s *FreeRadiusService) GetCurrentConfig() (string, error) {
	data, err := os.ReadFile(freeRadiusAuthorizePath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
