package services

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"strings"

	"sunipip-router-agent/internal/api"
)

// WireGuardService manages WireGuard tunnel configuration.
type WireGuardService struct {
	logger *slog.Logger
}

// NewWireGuardService creates a new WireGuard service manager.
func NewWireGuardService(logger *slog.Logger) *WireGuardService {
	return &WireGuardService{logger: logger}
}

// Apply writes WireGuard configs and brings up interfaces.
func (s *WireGuardService) Apply(ctx context.Context, cfg api.WireGuardConfig) error {
	s.logger.Info("Applying WireGuard configuration", "peers", len(cfg.Peers))

	for _, peer := range cfg.Peers {
		if err := s.writePeerConfig(peer); err != nil {
			return fmt.Errorf("write config for %s: %w", peer.Interface, err)
		}

		if err := s.restartInterface(ctx, peer.Interface); err != nil {
			return fmt.Errorf("restart %s: %w", peer.Interface, err)
		}
	}

	s.logger.Info("WireGuard configuration applied successfully")
	return nil
}

// writePeerConfig generates a WireGuard config file.
func (s *WireGuardService) writePeerConfig(peer api.WireGuardPeer) error {
	var b strings.Builder
	b.WriteString("# Generated by SuniPIP Router Agent\n")
	b.WriteString("# DO NOT EDIT - This file is managed automatically\n\n")

	b.WriteString("[Interface]\n")
	b.WriteString(fmt.Sprintf("PrivateKey = %s\n", peer.PrivateKey))
	b.WriteString(fmt.Sprintf("Address = %s\n", peer.Address))
	if peer.MTU > 0 {
		b.WriteString(fmt.Sprintf("MTU = %d\n", peer.MTU))
	}
	if peer.Table != "" {
		b.WriteString(fmt.Sprintf("Table = %s\n", peer.Table))
	}

	b.WriteString("\n[Peer]\n")
	b.WriteString(fmt.Sprintf("PublicKey = %s\n", peer.Peer.PublicKey))
	b.WriteString(fmt.Sprintf("Endpoint = %s\n", peer.Peer.Endpoint))
	b.WriteString(fmt.Sprintf("AllowedIPs = %s\n", peer.Peer.AllowedIPs))
	if peer.Peer.PersistentKeepalive > 0 {
		b.WriteString(fmt.Sprintf("PersistentKeepalive = %d\n", peer.Peer.PersistentKeepalive))
	}

	if err := os.MkdirAll("/etc/wireguard", 0700); err != nil {
		return fmt.Errorf("create wireguard dir: %w", err)
	}

	path := fmt.Sprintf("/etc/wireguard/%s.conf", peer.Interface)
	if err := writeFileAtomic(path, []byte(b.String()), 0600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	s.logger.Debug("Wrote WireGuard config", "interface", peer.Interface, "path", path)
	return nil
}

// restartInterface brings down and back up a WireGuard interface.
func (s *WireGuardService) restartInterface(ctx context.Context, iface string) error {
	// Bring down if already up (ignore errors - may not be up)
	downCmd := exec.CommandContext(ctx, "wg-quick", "down", iface)
	downCmd.Run() // intentionally ignore error

	// Bring up
	upCmd := exec.CommandContext(ctx, "wg-quick", "up", iface)
	if output, err := upCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("wg-quick up %s: %w (output: %s)", iface, err, string(output))
	}

	s.logger.Debug("WireGuard interface restarted", "interface", iface)
	return nil
}

// IsRunning checks if a WireGuard interface is active.
func (s *WireGuardService) IsRunning(ctx context.Context) bool {
	// Check if any wg interface is present
	cmd := exec.CommandContext(ctx, "wg", "show", "interfaces")
	output, err := cmd.Output()
	if err != nil {
		return false
	}
	return strings.TrimSpace(string(output)) != ""
}

// GetInterfaceStatus returns the wg show output for drift detection.
func (s *WireGuardService) GetInterfaceStatus(ctx context.Context, iface string) (string, error) {
	cmd := exec.CommandContext(ctx, "wg", "show", iface)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("wg show %s: %w", iface, err)
	}
	return string(output), nil
}

// GetCurrentConfig reads a WireGuard config file for drift detection.
func (s *WireGuardService) GetCurrentConfig(iface string) (string, error) {
	path := fmt.Sprintf("/etc/wireguard/%s.conf", iface)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(data), nil
}
